<?php
// Version 2.0; Agreement

$txt['registration_agreement_body'] = 'U stemt ermee in, door gebruik te maken van dit forum, dat je elk materiaal dat vals, lasterlijk, onjuist, beledigend, vulgair, hatelijk, kwetsend, obsceen, seksueel georiënteerd, bedreigend, inbreukmakend op iemands privacy, erotisch materiaal is niet zal plaatsen , of anderszins in strijd met de wetgeving. U aanvaardt tevens geen auteursrechtelijk beschermd materiaal te posten, tenzij u het copyright bezit of u toestemming van de eigenaar van het auteursrechtelijk beschermde materiaal heeft gekregen. Spam, flooding, advertenties, kettingbrieven, piramidespelen, en petities is ook verboden op dit forum.

Merk op dat het onmogelijk is voor het personeel of de eigenaars van dit forum om de geldigheid van de berichten te bevestigen. Vergeet niet dat wij niet actief toezicht houden op de geplaatste berichten, en als zodanig, zijn we niet verantwoordelijk voor de inhoud die wordt geplaatst. Wij kunnen de juistheid, volledigheid of bruikbaarheid van de gepresenteerde informatie niet garanderen. De geposte berichten drukken de meningen van de auteur, en niet noodzakelijk de mening van dit forum uit, haar personeel, haar dochterondernemingen of de eigenaar van dit forum. Iedereen die vindt dat een geplaatst bericht verwerpelijk is wordt aangemoedigd om een beheerder of moderator van dit forum onmiddellijk in kennis te stellen. Het personeel en de eigenaar van dit forum behouden het recht om bezwaarlijke berichten te verwijderen binnen een redelijke tijdspanne, als zij vinden dat verwijderen noodzakelijk is. Dit is een handmatig proces, dus houd er rekening mee dat we niet altijd in staat zijn om bepaalde berichten onmiddellijk te verwijderen of te bewerken. Dit beleid geldt ook voor lid profielgegevens.

U blijft zelf verantwoordelijk voor de inhoud van uw geposte berichten. Bovendien gaat u ermee akkoord de eigenaren van dit forum, alle gerelateerde websites op dit forum, haar personeel en haar dochterondernemingen te vrijwaren. De eigenaren van dit forum heeft ook het recht om je identiteit (of enige andere informatie vergaard op dit forum) in het geval van een formele klacht of juridische stappen als gevolg van een situatie die is ontstaan ​​door jouw gebruik van dit forum te onthullen.

Je hebt de mogelijkheid, als u zich registreert, om uw gebruikersnaam te kiezen. Wij adviseren dat u een normale naam gebruikt. Met dit gebruikersaccount u bent bijna op het punt om te registreren , gaat u ermee akkoord dat je niet het wachtwoord afgeeft aan een andere persoon m.u.v een beheerder, dit is voor je eigen bescherming en rechtsgeldigheid. Tevens verklaart u een account van een ander NOOIT te gebruiken om welke reden dan ook. We adviseren om een moeilijk te achterhalen wachtwoord te gebruiken voor uw account, om account diefstal te voorkomen.

Na geregistreerd en ingelogd te zijn om het forum,is er de mogelijkheid om een gedetailleerd profiel in te vullen. Het is uw verantwoordelijkheid om accurate informatie te presenteren. Alle informatie die de forum eigenaar of de staf als onjuist of vulgair bestempeld zal worden verwijderd, met of zonder voorafgaande verwittiging. Passende sancties kunnen volgen.

Let wel met elk bericht, wordt uw IP-adres geregistreerd,dit is nodig voor het geval dat je moet worden verbannen van dit forum of wanneer uw ISP gecontacteerd moet worden. Dit zal alleen gebeuren in het geval van een ernstige schending van deze overeenkomst.

Merk ook op dat de software een cookie, een klein tekstbestand met stukjes informatie (zoals uw gebruikersnaam en wachtwoord),plaatst in de cache van je browser. Dit wordt alleen gebruikt om het in en uitloggen op dit forum op te slaan . De software slaat geen computer gegevens of een andere vorm van gegevens in de cache van je browser op. Dit wordt alleen gebruikt in / uit loggen sessie te onthouden. De software slaat geen gegevens op uw computer op.';
